### 특정 조직에 해당 멤버가 속해있는것이 맞는가 여부 확인
GET http://133.186.209.25:8888/api/account/organizations/1/members/testId2
Content-Type: application/json

### 멤버가 속한 조직 제외한 나머지 조직 리스트 들고 오기
GET http://133.186.209.25:8888/api/account/organizations/members-without
X-USER-ID: testId4

### 멤버가 속한 조직 리스트 들고 오기
GET localhost:8090/api/account/organizations/members
X-USER-ID: testId1111

### 특정 조직에서 state와 role에 따라 멤버 들고오기
GET localhost:8090/api/account/organizations/1/members/state?state=1&role=ROLE_OWNER

### 추가
POST http://133.186.209.25:8888/api/account/organizations/3/members
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJtZW1iZXJJZCI6ImFkbWluIiwibWVtYmVyRW1haWwiOiJhMDEwNjI3MDQzMTJAZ21haWwuY29tIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTcxNTIzMzcxOSwiZXhwIjoxNzE1MjM3MzE5fQ.TwCt5bbUe1IlTST25GlhWd1aHXaPYqDrFlVPUBkXYJrdvv0_ZZkm6PMalO8ed-9vlGMDNLRWovLMKkaw_817cA


### state 수정
PUT localhost:8090/api/account/organizations/1/members?state=2
X-USER-ID: testId4

### memberOrgs 삭제
DELETE localhost:8090/api/account/organizations/331/members
X-USER-ID: testId9

### 조직 추가
POST http://133.186.209.25:8888/api/account/organizations
Content-Type: application/json
Accept: application/json

{
  "organizationName": "nhn 대전",
  "gatewaySn": "dsfsfsfs",
  "controllerSn": null
}

### 모든 조직 조회
GET http://133.186.209.25:8888/api/account/organizations
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJtZW1iZXJJZCI6ImFkbWluIiwibWVtYmVyRW1haWwiOiJhMDEwNjI3MDQzMTJAZ21haWwuY29tIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTcxNTIxOTE2MiwiZXhwIjoxNzE1MjIyNzYyfQ.owhtadwcghGtuP4EjVoVpiV5CuukuX_B99_gwsBh56hYgN-MTIP8G3PM7g8qWvqSeZZI8JtMu2ICCHkYLyIs8g

### 모든 조직 조회
GET http://133.186.218.201:8090/api/account/organizations
Content-Type: application/json
Accept: application/json

### 조직 추가
POST http://133.186.218.201:8090/api/account/organizations
Content-Type: application/json
Accept: application/json

{
  "organizationName": "nhn 대전",
  "gatewaySn": "dsfsfsfs",
  "controllerSn": null
}

### 조직 삭제
DELETE http://133.186.209.25:8888/api/account/organizations/3
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJtZW1iZXJJZCI6ImFkbWluIiwibWVtYmVyRW1haWwiOiJhMDEwNjI3MDQzMTJAZ21haWwuY29tIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTcxNTMwMzIzOCwiZXhwIjoxNzE1MzA2ODM4fQ.MSjJgd5i1Ue8_JdoDDkc4OMvdYOW_AitifThjWbgqUSsKrcQEahthZaHyZVGx-cbKT8XQecTReZGxeLkyIyJoA

### 오너 대기 상태 변경
PUT http://localhost:8090/api/account/member/modify/state
Content-Type: application/json
Accept: application/json

{
  "memberId" : "owner1",
  "stateId" : 1
}

###
GET http://localhost:8099/api/sensor/org/1/sensor
Content-Type: application/json

###
GET localhost:8090/api/account/organizations/1/members/state?state=1&role=ROLE_OWNER
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJtZW1iZXJJZCI6ImFkbWluIiwibWVtYmVyRW1haWwiOiIxMjMuMTIzLmNvbSIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX0FETUlOIn1dLCJpYXQiOjE3MTU2NDk5NTksImV4cCI6MTcxNTY1MzU1OX0.0gsaxkfBxCISAgSaoUG9NQBNvQjIYC50OsBdXXUG-0StOjlt7gx1DMNk8F-qvksiqmCZkUtF1CLzVdsLXsAFEA