POST http://133.186.209.25:8888/api/account/member/register
Content-Type: application/json

{
  "id": "test1",
  "password": "1234",
  "email" : "test@test.com"
}

###
POST http://133.186.209.25:8888/auth/login
Content-Type: application/json

{
  "id": "owner",
  "password": "123"
}

###
POST http://133.186.209.25:8888/api/account/member/register
Content-Type: application/json

{
  "id": "owner2",
  "password": "123",
  "email": "owner1@test.com",
  "roles": 2
}

###
GET http://133.186.209.25:8888/api/account/member/duplicate/test Od

###
POST http://133.186.209.25:8888/api/account/member/email/send
Content-Type: application/json

{
  "email": "skcogus12@n"
}

###
POST http://133.186.209.25:8888/api/account/member/email/verify
Content-Type: application/json

{
  "email": "skcogus12@naver.com",
  "certificationNumber": "538015"
}
