POST http://133.186.209.25:8888/api/account/member/register
Content-Type: application/json

{
  "id": "test1",
  "password": "1234",
  "email" : "test@test.com"
}

###
POST http://133.186.209.25:8888/auth/login
Content-Type: application/json

{
  "id": "admin",
  "password": "12345"
}

###
POST http://133.186.209.25:8888/api/account/member/register
Content-Type: application/json

{
  "id": "viewer1",
  "password": "123",
  "email": "admin@test.com",
  "roles": 1
}

###
GET http://133.186.209.25:8888/api/account/member/duplicate/testIOd

###
POST http://133.186.209.25:8888/api/account/member/email/send
Content-Type: application/json

{
  "email": "skcogus12@nave"
}

###
POST http://133.186.209.25:8888/api/account/member/email/verify
Content-Type: application/json

{
  "email": "skcogus12@naver.com",
  "certificationNumber": "538015"
}
